stages:
  - build
  - train
  - deploy

build:
  stage: build
  script:
    - docker buildx build -t training_pipeline -f training.Dockerfile .
    - docker buildx build -t prediction_pipeline -f prediction.Dockerfile .

train:
  stage: train
  script:
    - docker run -v ${PWD}/artifacts:/app/artifacts -v ${PWD}/logs:/app/logs -v ${PWD}/mlruns:/app/mlruns -v ${PWD}/config/:/app/config -v ${PWD}/params:/app/params  -v ${PWD}/source_files:/app/source_files training_pipeline
  artifacts:
    paths:
      - model/

deploy:
  stage: deploy
  script:
    - docker run -v ${PWD}/artifacts:/app/artifacts -v ${PWD}/logs:/app/logs prediction_pipeline