stages:
  - build
  - train
  - deploy

build:
  stage: build
  script:
    - docker buildx build -t training_pipeline -f training.Dockerfile .
    - docker buildx build -t prediction_pipeline -f prediction.Dockerfile .

train:
  stage: train
  script:
    - $PARENT_DIR = "C:\KBBOX"
    - docker run -v $PARENT_DIR/artifacts:/app/artifacts -v $PARENT_DIR/logs:/app/logs -v $PARENT_DIR/mlruns:/app/mlruns -v $PARENT_DIR/config/:/app/config -v $PARENT_DIR/params:/app/params  -v $PARENT_DIR/source_files:/app/source_files training_pipeline

deploy:
  stage: deploy
  script:
    - $PARENT_DIR = "C:\KBBOX"
    - docker run -v $PARENT_DIR/artifacts:/app/artifacts -v $PARENT_DIR/logs:/app/logs -p 5000:5000 prediction_pipeline
<<<<<<< HEAD
=======

>>>>>>> 672df3201c14e2e4f8ed47759ab62012711d8a0d
