stages:
  - build
  - train
  - deploy

build:
  stage: build
  script:
    - docker buildx build -t training_pipeline -f training.Dockerfile .
    - docker buildx build -t prediction_pipeline -f prediction.Dockerfile .


train:
  stage: train
  script:
    - docker run -v %cd%/artifacts:/app/artifacts -v %cd%/logs:/app/logs -v %cd%/mlruns:/app/mlruns -v %cd%/config/:/app/config -v %cd%/params:/app/params  -v %cd%/source_files:/app/source_files training_pipeline
  artifacts:
    paths:
      - model/
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker run -v %cd%/artifacts:/app/artifacts -v %cd%/logs:/app/logs prediction_pipeline
  only:
    - master