data_ingestion:
  root_dir: artifacts/data_ingestion
  source_files_path: source_files/files.zip
  

data_transform:
  root_dir: artifacts/data_transform
  raw_members_data_path: artifacts/data_ingestion/members_v3.csv
  raw_transactions_data_path: artifacts/data_ingestion/transactions_v2.csv
  raw_user_logs_data_path: artifacts/data_ingestion/user_logs_v2.csv
  raw_train_data_path: artifacts/data_ingestion/train_v2.csv
  final_X_train_data_path: artifacts/data_transform/X_train
  final_X_test_data_path: artifacts/data_transform/X_test
  y_train_data_path: artifacts/data_transform/y_train
  y_test_data_path: artifacts/data_transform/y_test

model_train:
  root_dir: artifacts/model_train
  X_train_data_path: artifacts/data_transform/X_train.npy
  X_test_data_path: artifacts/data_transform/X_test.npy
  y_train_data_path: artifacts/data_transform/y_train.npy
  y_test_data_path: artifacts/data_transform/y_test.npy
  final_model_path: artifacts/model_train/model.pkl